### ISSUE TITLE
Terraform Provisionner

### ISSUE THREAD

**Issue by gbergere** [coderanger/kitchen-kubernetes#8]
Hello, 

I'm not sure it's relevant here but would it be possible to make it work with Terraform provisionner?
The idea would be to use it to test a Kubernetes terraform module.

So we can terraform a Kubernetes cluster (as a terraform module) and use this `kitchen-kubernetes` to test our module with some Kubernetes tests.

Thanks a lot for you help
Geoffrey

**Comment by coderanger** [comment]
No, this is not related to what you are trying to do. This driver is for using K8s to make pseudo test VMs, not testing K8s itself.

**Comment by gbergere** [comment]
My bad it's a kubernetes verifier, I need. Any idea where I could find this?

Thanks

**Comment by coderanger** [comment]
I don't know of any.
